engines:
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - src/**
exclude_paths:
- "__tests__/**"
- "__test__/**"
- "__mocks__/**"
- "examples/**"
- "lib/**"
- "dist/**"
